#!/usr/bin/env bash

icon=""
# icon=" "

load="$(cut -d\  -f1 /proc/loadavg)"
cpus="$(nproc)"

printf "%s  %s\n" "$icon" "$load"
printf "%s %s\n" "$icon" "$load"
printf -v load_int "%.0f" "$load"
if [[ $load_int -gt $cpus ]]; then
	printf "#%s\n" "$BASE16_COLOR_08_HEX"
	exit 33
else
	printf "#%s\n" "$BASE16_COLOR_0B_HEX"
fi
